### ISSUE TITLE
Option to Synchronize AMT clock using RPC-GO local command

### ISSUE THREAD

**Issue by graikhel-intel** [open-amt-cloud-toolkit/rpc-go#317]
As a rpc-go user, I want to synchronize AMT clock to OS time using rpc-go local command.

1. We can make use of configure subcommand: **rpc configure syncclock -amtpassword password**
2. Should we consider using **rpc configure -config config.yaml** for all subcommands, similar to RPS profile.

**For example, see the config.yaml. MEBx password, sync clock and wificonfigs should all be configured with rpc configure -config.yaml command.**
```
mebxPassword: 'MEBX_PASSWORD'
syncronizeClock: true #Sync host OS clock to AMT
wifiConfigs:
  enablePort: true
  wifiProfileSync: true 
  - profileName: 'exampleWifiWPA2'
    ssid: 'exampleSSID'
    priority: 1
    authenticationMethod: 6
    encryptionMethod: 4
    pskPassphrase: ''
  - profileName: 'exampleWifi8021x'
    ssid: 'ssid'
    priority: 2
    authenticationMethod: 7
    encryptionMethod: 4
    ieee8021xProfileName: 'exampleIeee8021xEAP-TLS'
ieee8021xConfigs:
  - profileName: 'exampleIeee8021xEAP-TLS'
    username: "exampleUserName"
    password: ""
    authenticationProtocol:
    clientCert: ''
    caCert: ''
```

### Acceptance Criteria:
- [ ] Should be able to synchronize AMT clock using rpc-go local configure command
