### ISSUE TITLE
Feature Request: Pass config.yaml to `rpc configure tls` command

### ISSUE THREAD

**Issue by bwendlandt-intel** [open-amt-cloud-toolkit/rpc-go#485]
I would like to be able to pass a config.yaml file using a `-config` flag to the `configure tls` command. In the yaml, I would like to be able to pass EA credentials and server mode.

Example config.yaml:
```
tls:
  mode: 'Server'
enterpriseAssistant:
  eaAddress: 'http://192.168.1.20:8000'
  eaUsername: 'admin'
  eaPassword: 'Password123!'
```
